config/routes.rb
NativetongueWebsite::Application.routes.draw do
  resources :enquiries

  match '/robots.txt' => 'home#robots'

  match '/app-consulting' => 'home#app_consulting', :as => 'consulting'
  match '/letterpress-game-strategy-guide' => 'home#lp_strategy', as: 'lp_strategy'
  match '/' => 'home#app_consulting', :constraints => {:subdomain => 'apps'}
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
  attr_accessible :content, :email, :name
  validates_presence_of :email, :name
end

app/models/enquiry_observer.rb
class EnquiryObserver < ActiveRecord::Observer
  def after_create(enquiry)
    EnquiriesMailer.received(enquiry).deliver
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

  before_filter do
    headers['Cache-Control'] = 'public; max-age=86400'
  end
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  respond_to :json, :html

  def create
    @enquiry = Enquiry.create!(name: params[:name], email: params[:email], content: params[:content])
    respond_with(@enquiry)
  end

  def index
    respond_with(@enquiries = Enquiry.all)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def app_consulting
  end
  def lp_strategy
  end

  def robots
    render :file => Rails.root + "config/robots.#{Rails.env}.txt", layout: false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

  # Implements the world-famous Paul Irish IE conditional comments HTML tag--in HAML
  # http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
  def cc_html(options={}, &blk)
    attrs = options.map { |(k, v)| " #{h k}='#{h v}'" }.join('')
    [ "<!--[if lt IE 7]> <html#{attrs} class='lt-ie9 lt-ie8 lt-ie7'> <![endif]-->",
      "<!--[if IE 7]>    <html#{attrs} class='lt-ie9 lt-ie8'> <![endif]-->",
      "<!--[if IE 8]>    <html#{attrs} class='lt-ie9'> <![endif]-->",
      "<!--[if gt IE 8]><!--> <html#{attrs} class=''> <!--<![endif]-->",
      capture_haml(&blk).strip,
      "</html>"
    ].join("\n")
  end

  def h(str); Rack::Utils.escape_html(str); end
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/app_consulting.html.haml
%section.mod-intro
  .layout-wrap
    .heading
      %h1
        Mobile Applications Consulting Services
      %ul.os
        %li.android Android
        %li.ios iOS
      .contact
        = link_to 'Enquire Now', '#enquiryModal', class:'enquire', role:"button", "data-toggle"=>"modal", "data-loading-text"=>"Sending..."
        %span or
        = link_to 'tel:1300792720', :class => 'call' do
          = image_tag 'i_phone_white.png'
          1300 792 720


  .illustration
    = image_tag 'illustration.png'

  .layout-wrap{:style => 'margin-top: -200px'}
    %section.mod-why_us
      %h1 Why us?
      %ul
        %li
          %h2.mobile Multi Platform Specialists
          We specialise in building for both ios and android platforms simultaneously saving time and money.
        %li
          %h2.people Experienced Team
          We've developed 5 apps as a team and have combined web/mobile production experience of over 25 years.
        %li
          %h2.experience More than Just Developers
          Our experience comprises everything it takes to bring an app to market so we can provide valuable marketing and ASO advice and insight
        -#%li
        -#  %h2.drawer Proin Fermentum est sed
        -#  Mauris sed elit in nunc vulputate porta nec vel nunc. Nam hendrerit elt leo vitae dui rhoncus adipiscing lorem ipsum dolor sit amet.
        -#%li
        -#  %h2.suitcase Suspendisse Accumsan
        -#  Quisque sollicitudin purus at augue hendrerit non elementum ipsum auctor. In dignissim urna et odio dunt aliquet.
        -#%li
        -#  %h2.bucket Aliquam dolor eu mi
        -#  We've developed 5 apps as a team and have combined web/mobile production experience of over 25 years.
        -#%li
        -#  %h2.graph Mauris ac adipiscing eros
        -#  Our experience comprises everything it takes to bring an app to market so we can provide valuable marketing and ASO advice and insight
        -#%li
        -#  %h2.globe Fames ac turpis egestas
        -#  Mauris sed elit in nunc vulputate porta nec vel nunc. Nam hendrerit elt leo vitae dui rhoncus adipiscing lorem ipsum dolor sit amet.

%section.mod-steps
  .layout-wrap
    %h1
      Our Process
    %ol
      %li.contact
        %h2 1. You get in Contact
        %div You make initial contact by sending us an email or Calling our Customer Service Team.
      %li.consultation
        %h2 2. Consultation/Workshop
        %div We conduct a 1 hour Initial Consultation, which will detail every important project feature.
      %li.return
        %h2 3. Ball park estimate and approach selection
        %div You will receive an indicative estimate of time and cost. Then, you choose the approach that suits you best.

%section.mod-approaches
  .layout-wrap
    %h1
      Our 2 Approaches

    .image
      = image_tag 'approaches.png'

    %div
      .approach
        %h2
          %span.second Approach
          \#1 - Fixed
          %span.first Price

        %p.blurb
          Scoping exercise, the exact cost of which depends on the outcome of the initial consultation. The output of the scoping phase is: -
          %b Wireframes for Every Screen
          descriptions of functions and
          %b Business Rules Captured as User Stories.

        %h3.star Features
        %ul.features
          %li Fixed Price Quote
          %li Agreement to Proceed
          %li Deposit of 25%
          %li Complete Graphic Design
          %li Development and Test - weekly progress meetings and "showcase" of app to date
          %li Progress Payments at 25%, 50% and 75%
          %li Development Completion
          %li Final Testing and Acceptance
          %li Final Payment of balance
          %li Submission to App Store (publishing arrangements TBD)

        %h3.up Advantages
        %ul.advantages
          %li Cost Certainty

        %h3.down Disadvantages
        %ul.disadvantages
          %li More Expensive
          %li Changes to scope or time are difficult and expensive
          %li Limited Flexibility to launch earlier or reduce features
          %li Larger Cost Commitment

      .approach
        %h2
          %span.second Approach
          \#2 - Agile
          %span.first Time & Materials

        %p.blurb
          Devise Team make-up and consequent weekly cost of team.

        %h3.star Features
        %ul.features
          %li Agreement to proceed
          %li Deposit equivalent to cost of 2 weeks
          %li
            Scoping workshop. The output of the scoping phase is:
            %ul
              %li wireframes for most important screens
              %li high level descriptions of functions and business rules captured as "epic" User Stories
          %li Initial graphic design - the main screen and one or two typical screens to establish the overall look and feel
          %li
            Weekly cycles of:
            %ul
              %li Feature Planning
              %li Development & Test
              %li Review and Capture refinements/changes.
          %li Fortnightly payments in arrears on 7 day terms
          %li Submission to app store (publishing arrangements TBD) at the conclusion of any weekly cycle

        %h3.up Advantages
        %ul.advantages
          %li Less Expensive
          %li More Control over the features and priorities on a weekly basis
          %li Ability to launch at any time
          %li Changes are easy and inexpensive
          %li Smaller Cost Commitment

        %h3.down Disadvantages
        %ul.disadvantages
          %li No Cost Certainty
          %li Higher Risk of "feature bloat"

%section.mod-testimonials
  .layout-wrap
    .quote
      %h1 What the Critics Say
      %ul
        %li
          %blockquote
            %h2 "An impressive education app!"
            Mandarin Madness (by Native Tongue) is an impressive education app that introduces 240+ Chinese words throughout 41 levels and 3 stages of arcade gaming fun, providing a very memorable learning experience.
            %footer - Crazy Mikes, crazymikesapps.com

    .quote
      %h1 What our users say
      %ul
        %li
          %blockquote
            %h2 "It's like eating broccoli that tastes like cookies"
            I love your app "mandarin madness". The engagement is amazing, the aesthetics (music/illustration) are incredible.
            %footer - Bruce Flaherty, Minnesota
#enquiryModal.modal.hide.fade{tabindex:"-1", role:"dialog", "aria-labelledby"=>"myModalLabel", "aria-hidden"=>"true"}
  .modal-header
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    %h3 How can we help?
  .modal-body
    =simple_form_for Enquiry.new do |f|
      = f.input_field :name, label: false, placeholder: "Your name?", pattern: " *[^ ]+.*", required: true
      = f.input_field :email, label: false, placeholder: "Email and/or phone number", as: :string, required: true, pattern: ".*\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}\\b.*|.*\\b[0-9]{10,15}\\b.*"
      = f.input :content, label: false, placeholder: "Tell us a little about your idea or needs...", as: :text, hint: "We'll never spam you or give your details to anyone else, ever, unless required to by law."
  .modal-footer
    = link_to 'Send', "#", class: "btn btn-primary", id: "send_enquiry_button"

#infoModal.modal.hide.fade{tabindex:"-1", role:"dialog", "aria-labelledby"=>"myModalLabel", "aria-hidden"=>"true"}
  .modal-header
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    %h3 Thank You
  .modal-body
    Thank you very much for your enquiry. One of our consultants will contact you within the next 24 hours to arrange a
    time to discuss your requirements in more detail.
  .modal-footer
    = link_to 'Close', "#", class: "btn btn-primary", id: "close_info_modal_button", "data-dismiss" => "modal"

:javascript
  window.enquiries_context = {enquiries_url: '#{enquiries_url}', auth_token: '#{form_authenticity_token}'}

app/views/home/index.html.haml
%section.mod-intro
  .layout-wrap
    .heading
      %h1
        Innovative Mobile Apps & Games
        %span that help people learn a second language.

      %ul.os
        %li.android Android
        %li.ios iOS

  .map
    = image_tag 'apps.png', :alt => 'Screenshots of Native Tongue apps', :class => 'screenshots'

    .marker_container
      .marker.bubble1{:style => 'top: 240px; left: 230px'}
        = image_tag 'avatar.png'
        %p
          It's like eating broccoli that tastes like cookies. I love your app "mandarin madness". The engagement is amazing, the aesthetics (music/illustration) are incredible.
          %b (Bruce Flaherty, Minnesota)

      .marker.bubble2{:style => 'top: 280px; left: 460px'}
        = image_tag 'avatar.png'
        %p
          Great for getting to know vocab, probably my favourite game on android right now, great development A+++
          %b (Spanish Smash review, Google Play)

      .marker.bubble3{:style => 'top: 240px; left: 750px'}
        = image_tag 'avatar.png'
        %p
          Really helped me and in a short time as well. I'm so bad at remembering things, and didn't really think it was going to help but it really did straight away :)
          %b (Maddellyn, iTunes Store)

  .layout-wrap
    %ul.apps
      %li
        Mandarin Madness
        %ul
          %li= link_to 'iPhone & iPad', 'https://itunes.apple.com/app/learn-chinese-mandarin-madness/id494800742?mt=8', :class => 'button ios'
          %li= link_to 'Android', '#', :class => 'button android'
          %li= link_to 'Kindle Fire', '#', :class => 'button kindle'
      %li
        Spanish Smash
        %ul
          %li= link_to 'iPhone & iPad', 'https://itunes.apple.com/app/learn-spanish-spanish-smash/id524637598?mt=8', :class => 'button ios'
          %li= link_to 'Android', '#', :class => 'button android'
          %li= link_to 'Kindle Fire', '#', :class => 'button kindle'
      %li
        English Eruption
        %ul
          %li= link_to 'iPhone & iPad', 'https://itunes.apple.com/app/learn-english-english-eruption/id505864135?mt=8', :class => 'button ios'
          %li= link_to 'Android', '#coming-soon', :class => 'button android coming-soon'
          %li= link_to 'Kindle Fire', '#coming-soon', :class => 'button kindle coming-soon'

    %section.mod-usp
      %h1 Forget Boring flash cards. Play a game instead!
      %ul.left
        %li Learn more quickly than with flash cards.
        %li Learn to recognize both the text as well as the sound, spoken by a native speaker.
        %li 3 stages and 41 levels that each get progressively more difficult to ensure your mastery of a set of words.
      %ul
        %li Fun arcade style gameplay that makes learning vocabulary fun instead of tedious.
        %li Ideal for beginner – intermediate language students.
        %li Ideal for travellers to pick up some useful vocabulary whilst on the plane, train, bus or boat.

%section.mod-reviews
  .layout-wrap
    .industry.quote
      %h1 Industry Reviews
      %ul
        %li
          %blockquote
            A gem of a learning application, with a great concept for combining education and gaming fun.
            %footer - Michael Vallez, Crazy Mike’s App
      = link_to 'previous', '#', :class => 'prev'
      %span.next next

    .press.quote
      %h1 Media Press
      %ul
        %li
          %blockquote
            Before you know it you can count to ten, or know how to talk about basic clothing. This app is great for ages young and old.
            %footer - Matt Beeche, Shoe String Startups
      %span.prev previous
      = link_to 'next', '#', :class => 'next'

-#.layout-wrap
-#  %section.mod-subscribe
-#    %h1 Fill Out the form below and Receive Free Updates!
-#    %form{:method => 'post', :action => '#'}
-#      .group
-#        %label{:for => 'firstname'} First Name:
-#        %input#firstname{:type => 'text'}
-#      .group
-#        %label{:for => 'email'} Email Address:
-#        %input#email{:type => 'email'}
-#      .group.last
-#        %span.label Preferred Format:
-#        %label.radio
-#          %input{:type => 'radio', :name => 'emailtype', :checked => 'checked'} HTML
-#        %label.radio
-#          %input{:type => 'radio', :name => 'emailtype'} Text
-#        %label.radio
-#          %input{:type => 'radio', :name => 'emailtype'} Mobile
-#        %input{:type => 'submit', :value => 'Submit'}

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Nativetongue Website", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', users_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!! 5
!= cc_html(lang: 'en') do
  %head
    %meta{:charset => 'utf-8'}
    %meta{:name => 'viewport', :content => 'width=device-width, initial-scale=1'}
    %title Native Tongue
    = javascript_include_tag 'modernizr'
    = javascript_include_tag 'http://use.typekit.net/xnu0xvp.js'
    :javascript
      try{Typekit.load();}catch(e){}
    = stylesheet_link_tag 'application'

  %body
    %header.mod-header#mod-header.layout-wrap
      %h1.logo= link_to 'Native Tongue', '/'

      %nav
        %ul
          %li= link_to 'Home', '/', :class => 'home'
          -#%li= link_to 'About Us', '#'
          -#%li= link_to 'Our Blog', '#'
          %li= link_to 'Need an App?', consulting_path
          -#%li= link_to 'Schools', '#'
          -#%li= link_to 'Press', '#'
          %li= link_to 'LP Strategy', lp_strategy_path
          -#%li= link_to 'Contact', '#'
          %li.twitter= link_to 'Follow Us', 'https://twitter.com/nativetonguelab', :class => 'button twitter', id: 'custom-twitter-button'
          %li.facebook= link_to 'Like Us', 'http://www.facebook.com/nativetonguelab', :class => 'button facebook'
      .actual-twitter_button
        = link_to 'Follow Us', 'https://twitter.com/nativetonguelab', :class => 'twitter-follow-button', "data-show-count"=>"false", "data-lang"=>"en", id: 'actual-twitter-button'


    = yield

    %footer.mod-footer
      %h1 About Native Tongue
      .inner
        .layout-wrap
          .social
            %span.corner
            -#.facebook
            -#  %h2 <b>Native Tongue</b> on Facebook
            -#  .fb-like-box{"data-href"=>"http://www.facebook.com/nativetonguelab", "data-width"=>"292", "data-show-faces"=>"true", "data-stream"=>"true", "data-header"=>"true"}}

            .twitter
              %h2 Latest
              = link_to 'Tweets by @nativetonguelab', "https://twitter.com/nativetonguelab", class:"twitter-timeline", "data-widget-id" => "313188421508153344"
              :javascript
                !function(d,s,id){
                  var js,fjs=d.getElementsByTagName(s)[0];
                  if(!d.getElementById(id)){js=d.createElement(s);js.id=id;
                  js.src="//platform.twitter.com/widgets.js";
                  fjs.parentNode.insertBefore(js,fjs);}
                }(document,"script","twitter-wjs");

              -#%ul
              -#  %li 15 minutes ago - <a href="#">@lorem1973</a> Class aptent taciti sociosqu ad litora torquent per conubia nostra. <a href="#">#nativetongue2013</a>
              -#%span.prev previous
              -#= link_to 'next', '#', :class => 'next'

          .blog
            %h2 Latest Blog Posts
            %ul
              %li
                Our blog will be back soon...
              -#%li= link_to 'Language stories #1 – The Beijing Diaries', '#'
              -#%li= link_to 'Winners for the Spanish Is Your Amigo Promotion!', '#'
              -#%li= link_to 'Marketing For Mobile Apps – Tips And Tricks', '#'
              -#%li= link_to 'What are some Letterpress games won in very few turns?', '#'
              -#%li= link_to 'Win a Spanish lesson and textbook from Spanish Is Your Amigo', '#'

          .products
            %h2 Our Products
            %ul
              %li= link_to 'English Eruption', 'http://www.englisheruption.com'
              %li= link_to 'Mandarin Madness', 'http://www.mandarinmadness.com'
              %li= link_to 'Spanish Smash', 'http://www.spanishsmash.com'

          .contact
            %h2 Contact Us
            %address
              173 City Road, Melbourne, Australia
              %br
              %span.logo= link_to 'hello@nativetongue.com', 'mailto:info@nativetongue.com'

      .links.layout-wrap
        %p © 2011-2013 NativeTongue.com - All rights Reserved
        %ul
          %li= link_to 'Terms & Conditions', '#'
          %li= link_to 'Privacy Policy', '#'

    = javascript_include_tag 'application'
    #fb-root
    -#:javascript
    -#  (function(d, s, id) {
    -#    var js, fjs = d.getElementsByTagName(s)[0];
    -#    if (d.getElementById(id)) return;
    -#    js = d.createElement(s); js.id = id;
    -#    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=168575276558048";
    -#    fjs.parentNode.insertBefore(js, fjs);
    -#  }(document, 'script', 'facebook-jssdk'));
    :javascript
      if (!jQuery.browser.mobile) {
        window.$zopim||(function(d,s){
          var z=$zopim=function(c){z._.push(c)},$=z.s=d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set._.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
          $.src='//cdn.zopim.com/?140dc7y8i4YFonj7y7OgNkySshhlXa2U';
          z.t=+new Date;
          $.type='text/javascript';e.parentNode.insertBefore($,e)
        })(document,'script');
      }
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-27114051-1']);
      _gaq.push(['_setDomainName', 'nativetongue.com']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

app/views/layouts/layout.haml
!!! 5
!= cc_html(lang: 'en') do
  %head
    %meta{:charset => 'utf-8'}
    %meta{:name => 'viewport', :content => 'width=device-width, initial-scale=1'}
    %title Native Tongue
    = javascript_include_tag 'modernizr'
    = javascript_include_tag '//use.typekit.net/wpn6xkp.js'
    :javascript
      try{Typekit.load();}catch(e){}
    = stylesheet_link_tag 'application'

  %body
    %header.mod-header#mod-header.layout-wrap
      %h1.logo= link_to 'Native Tongue', '/'

      %nav
        %ul
          %li= link_to 'Home', '#', :class => 'home'
          %li= link_to 'About Us', '#'
          %li= link_to 'Our Blog', '#'
          %li= link_to 'Our Products', '#'
          %li= link_to 'Schools', '#'
          %li= link_to 'Press', '#'
          %li= link_to 'LP Strategy', '#'
          %li= link_to 'Contact', '#'
          %li.twitter= link_to 'Follow Us', '#', :class => 'button twitter'
          %li.facebook= link_to 'Like Us', '#', :class => 'button facebook'

    = yield

    %footer.mod-footer
      %h1 About Native Tongue
      .inner
        .layout-wrap
          .social
            %span.corner
            .facebook
              %h2 <b>Native Tongue</b> on Facebook
              [insert Facebook code]

            .twitter
              %h2 Latest <b>Tweets</b>
              %ul
                %li 15 minutes ago - <a href="#">@lorem1973</a> Class aptent taciti sociosqu ad litora torquent per conubia nostra. <a href="#">#nativetongue2013</a>
              %span.prev previous
              = link_to 'next', '#', :class => 'next'

          .blog
            %h2 Latest Blog Posts
            %ul
              %li= link_to 'Language stories #1 – The Beijing Diaries', '#'
              %li= link_to 'Winners for the Spanish Is Your Amigo Promotion!', '#'
              %li= link_to 'Marketing For Mobile Apps – Tips And Tricks', '#'
              %li= link_to 'What are some Letterpress games won in very few turns?', '#'
              %li= link_to 'Win a Spanish lesson and textbook from Spanish Is Your Amigo', '#'

          .products
            %h2 Our Products
            %ul
              %li= link_to 'English Eruption', '#'
              %li= link_to 'Mandarin Madness', '#'
              %li= link_to 'Spanish Smash', '#'

          .contact
            %h2 Contact Us
            %address
              2nd Floor, 456 Lorem Street - Consectetur Elit - W1B 3HH
              %br
              %span.logo= link_to 'info@nativetongue.com', 'mailto:info@nativetongue.com'

      .links.layout-wrap
        %p © 2001-2012 NativeTongue.com - All rights Reserved
        %ul
          %li= link_to 'Terms & Conditions', '#'
          %li= link_to 'Privacy Policy', '#'

    = javascript_include_tag 'application'

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Registered
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            = render user
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}